% TODO
% -make this a function called CreateDatabase(), CreateDatabase('filename', userinput)
% -optional parameter called filename
% -might need to navigate to target folder, create file, navigate back to original folder
% -otherwise name the data ./database/GCMS_Database.sql
% -load the samples_table_sql.txt --> load a text file and create table from it
% samples and peaks table

%% Create database
dbfile = "GCMS_Database.db";
conn = sqlite(dbfile, 'create');

%% Create table in database
sqlquery = ['create table samples( ' ...
    'sample_id       integer not null ' ...
        'constraint sample_id ' ...
            'primary key,' ...
    'sample_name     TEXT,' ...
    'file_name       TEXT    not null,' ...
    'file_path       TEXT    not null,' ...
    'sequence_number integer,' ...
    'file_checksum   TEXT    not null,' ...
    'file_size       TEXT    not null,' ...
    'file_version    TEXT,' ...
    'sample_info     TEXT,' ...
    'operator        TEXT    not null,' ...
    'datetime        TEXT    not null,' ...
    'datevalue       REAL    not null,' ...
    'instrument      TEXT    not null,' ...
    'instr_model     TEXT    not null,' ...
    'inlet           TEXT,' ...
    'method_name     TEXT    not null,' ...
    'sequence_name   TEXT    not null,' ...
    'sequence_path   TEXT    not null,' ...
    'sequence_index  REAL    not null,' ...
    'vial            REAL    not null,' ...
    'replicate       REAL    not null,' ...
    'injvol          REAL,' ...
    'glp_flag        REAL,' ...
    'data_source     REAL,' ...
    'firmware_rev    REAL,' ...
    'software_rev    REAL,' ...
    'start_time      REAL    not null,' ...
    'end_time        REAL    not null,' ...
    'sampling_rate   REAL    not null,' ...
    'time            REAL    not null,' ...
    'intensity       REAL    not null,' ...
    'channel         REAL,' ...
    'time_units      TEXT    not null,' ...
    'intensity_units TEXT,' ...
    'channel_units   TEXT,' ...
    'baseline        REAL    not null)'];

execute(conn, sqlquery);


%% Close connection
close(conn)