function library = getLibraryStructure()

% Set library data fields
library = struct(...
    'file_path',                [],...
    'file_name',                [],...
    'file_size',                [],...
    'compound_name',            [],...
    'compound_synonym',         {},...
    'compound_formula',         [],...
    'compound_mw',              [],...
    'compound_exact_mass',      [],...
    'compound_retention_time',  [],...
    'compound_retention_index', [],...
    'compound_ontology',        [],...
    'cas_id',                   [],...
    'nist_id',                  [],...
    'db_id',                    [],...
    'smiles',                   [],...
    'inchikey',                 [],...
    'ion_mode',                 [],...
    'collision_energy',         [],...
    'comments',                 [],...
    'num_peaks',                [],...
    'mz',                       [],...
    'intensity',                []);

end