function plotPeaksInData(data, sampleIndex)

cla; hold all;

% Plot TIC
plot( ...
    data(sampleIndex).time, ...
    data(sampleIndex).intensity(:,1), ...
    'color', 'black');

for i = 1:length(data(sampleIndex).peaks)
    
    % Plot peak fit
    plot( ...
        data(sampleIndex).peaks(i).fit(:,1), ...
        data(sampleIndex).peaks(i).fit(:,2), ...
        'color', 'blue', ...
        'linewidth', 2);

end

end