% Export NIST (preliminary function)

% function to save a peak as a NIST formatted data structure

% input will be sample info, peaks mass spectra (intensity(row, :)), and
% channel (1,:)

% function takes three inputs, 1: sample row, 2: peak mz array, 3: peak
% intensity array

% might be easier for it to just take in the data object here? 
function data = ExportNIST(sampleRow, dataRow)

% ---------------------------------------
% Data
% ---------------------------------------
data = struct(...
    'file_path',                [],...
    'file_name',                [],...
    'file_size',                [],...
    'compound_name',            [],...
    'compound_synonym',         {},...
    'compound_formula',         [],...
    'compound_mw',              [],...
    'compound_exact_mass',      [],...
    'compound_retention_time',  [],...
    'compound_retention_index', [],...
    'cas_id',                   [],...
    'nist_id',                  [],...
    'db_id',                    [],...
    'smiles',                   [],...
    'inchikey',                 [],...
    'ion_mode',                 [],...
    'collision_energy',         [],...
    'comments',                 [],...
    'num_peaks',                [],...
    'mz',                       [],...
    'intensity',                []);

channelData = dataRow.channel(1, :);
peakMassSpectra = dataRow.intensity(sampleRow, :);

data(1).mz = channelData;
data(1).intensity = peakMassSpectra;
data(1).compound_retention_time = dataRow.time(sampleRow, 1);
data(1).file_path = dataRow.file_path;
data(1).file_name = dataRow.file_name;
data(1).file_size = dataRow.file_size;