function nistData = ExportNIST(sampleData, peakRow)

% ------------------------------------------------------------------------
% Method      : ExportNIST()
% Description : saves peak data as a NIST formatted data structure
% ------------------------------------------------------------------------

% ---------------------------------------
% Data
% ---------------------------------------
nistData = struct(...
    'file_path',                [],...
    'file_name',                [],...
    'file_size',                [],...
    'date_created',             [],...
    'compound_name',            [],...
    'compound_synonym',         {},...
    'compound_formula',         [],...
    'compound_mw',              [],...
    'compound_exact_mass',      [],...
    'compound_retention_time',  [],...
    'compound_retention_index', [],...
    'compound_ontology',        [],...
    'cas_id',                   [],...
    'nist_id',                  [],...
    'db_id',                    [],...
    'smiles',                   [],...
    'inchikey',                 [],...
    'ion_mode',                 [],...
    'collision_energy',         [],...
    'comments',                 [],...
    'num_peaks',                [],...
    'mz',                       [],...
    'intensity',                []);

nistData(1).file_path = sampleData.file_path;
nistData(1).file_name = sampleData.file_name;
nistData(1).file_size = sampleData.file_size;

nistData(1).compound_retention_time = sampleData.peaks(peakRow).time;
nistData(1).num_peaks = length(sampleData.peaks(peakRow).mz);
nistData(1).mz = sampleData.peaks(peakRow).mz;
nistData(1).intensity = sampleData.peaks(peakRow).intensity;

if isfield(sampleData.peaks(peakRow), 'date_created')
    nistData(1).date_created = sampleData.peaks(peakRow).date_created;
else
    nistData(1).date_created = datestr(now(), 'yyyy-mm-ddTHH:MM:SS');
end

nistData(1).compound_name = '';
nistData(1).compound_synonym = '';
nistData(1).compound_formula = '';
nistData(1).compound_ontology = '';
nistData(1).cas_id = '';
nistData(1).nist_id = '';
nistData(1).db_id = '';
nistData(1).smiles = '';
nistData(1).inchikey = '';
nistData(1).ion_mode = '';
nistData(1).collision_energy = '';
nistData(1).comments = '';
nistData(1).compound_mw = NaN;
nistData(1).compound_retention_index = NaN;
nistData(1).compound_exact_mass = NaN;

end 